CREATE TABLE ACCOUNT (
	ID BIGSERIAL PRIMARY KEY,
	EMAIL VARCHAR(50) NOTNULL UNIQUE,
	PHONE VARCHAR(11) UNIQUE,
	USERNAME VARCHAR(50) NOTNULL UNIQUE,
	PASSWORD VARCHAR(100) NOTNULL,
	ROLE VARCHAR(20) DEFAULT 'USER',
	STATUS VARCHAR(20) DEFAULT 'ACTIVE',
	CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE PROFILE (
	ID BIGSERIAL PRIMARY KEY,
	ACCOUNT_ID BIGINT NOT NULL UNIQUE,
	URL_AVATAR VARCHAR(255),
	FULL_NAME VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE,
	BIO VARCHAR(255),
	CONSTRAINT FK_PROFILE_ACCOUNT 
		FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT (ID)
)

CREATE TABLE BUILDING (
	ID BIGSERIAL PRIMARY KEY,
	MANAGER_ID BIGINT NOT NULL UNIQUE,
	NAME VARCHAR(255) NOT NULL,
	FLOOR_NUMBER SMALLINT NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	STATUS VARCHAR(20) NOT NULL,
	CONSTRAINT FK_BUILDING_ACCOUNT 
		FOREIGN KEY (MANAGER_ID) 
		REFERENCES ACCOUNT (ID)
)

CREATE TABLE FLOOR(
	ID BIGSERIAL PRIMARY KEY,
	BUILDING_ID BIGINT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	ROOM_NUMBER SMALLINT NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_FLOOR_BUILDING 
		FOREIGN KEY (BUILDING_ID) 
		REFERENCES BUILDING (ID)
)