CREATE TABLE Account(
 id BIGSERIAL PRIMARY KEY,
 email VARCHAR(50) NOTNULL UNIQUE,
 phone VARCHAR(11) UNIQUE,
 username VARCHAR(50) NOTNULL UNIQUE,
 password VARCHAR(100) NOTNULL,
 role VARCHAR(20) DEFAULT 'USER',
 status VARCHAR(20) DEFAULT 'ACTIVE',
 create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Profile(
id BIGSERIAL PRIMARY KEY,
account_id BIGINT NOT NULL UNIQUE,
url_avatar VARCHAR(255),
full_name VARCHAR(50) NOT NULL,
birth_date DATE,
bio VARCHAR(255),
	CONSTRAINT fk_profile_account
		FOREIGN KEY (account_id)
		REFERENCES Account(id)
);

CREATE TABLE Building(
id BIGSERIAL PRIMARY KEY,
manager_id BIGINT NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
floor_number SMALLINT NOT NULL,
create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
status VARCHAR(20) NOT NULL,
	CONSTRAINT fk_building_account
		FOREIGN KEY (manager_id)
		REFERENCES Account(id)
)

CREATE TABLE Floor(
id BIGSERIAL PRIMARY KEY,
building_id BIGINT NOT NULL,
name VARCHAR(255) NOT NULL,
room_number SMALLINT NOT NULL,
create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_floor_building
		FOREIGN KEY (building_id)
		REFERENCES Building(id) 
)


